# Generated by Django 2.2 on 2019-04-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=3)),
                ('summary', models.TextField()),
                ('featured', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
